서버파트 1차 세미나 과제
30th-THE-SOPT-Server-Part/JinSu pull request #1
Opened 2022-04-08 13:01 UTC by jinsu4755

- [ ] 실천 과제 (Level 1) - 세미나에서 나온 코드들 직접 타이핑 하면서 익혀보기
- [ ] 발전 과제 (Level 2) - 주어진 서버 파트 멤버를 이용하여 OB-YB 랜덤 저녁 식사 짝을 정해주자

---
자스 타스가 처음이라 그냥 이것 저것 검색하면서 만들어서... 매우 코드가 나쁠.. 가능성이 높습니다...

리뷰 잘 부탁.. 늦어서 쏴리..

2022-04-08 15:34 UTC, epitone requested changes
닉값 하러 왔습니다.

2022-04-08 15:34 UTC, epitone commented on Seminar1/randomDinnerMatching/domain/dinnerMatcher.ts
> +        return members.sort(() => Math.random() - 0.5);
코드에서 상수로 선언되어 있지 않은 숫자, 문자열은 무엇을 의미하는지 제대로 알 수 없는 문제가 있습니다. 
따라서 그 의미를 파악하기 위해 클래스를 이해하고, 코드의 흐름을 이해하기 위한 시간과 노력이 필요하게 됩니다.

아래 링크를 통해 매직 넘버를 변경해보면 좋을 것 같아요!

출처 : https://javabom.tistory.com/28

ps. 상수는 상수를 잡는다.

2022-04-08 15:39 UTC, epitone commented on Seminar1/randomDinnerMatching/random.ts
> +const dinnerMatcher: DinnerMatcher = new SoptDinnerMatcher(memberDataSource);
memberDataSource라는 변수를 따로 활용하는 이유가 있을까요?

바로 MemberDataSource를 주입해서 사용하면 어떠할까요?

2022-04-08 15:39 UTC, jinsu4755 commented on Seminar1/randomDinnerMatching/domain/dinnerMatcher.ts
> +        return members.sort(() => Math.random() - 0.5);
오호 닉값 잘 받았습니다.. 아무래도 그냥 있는거 그대로 썼는데 지금보니까 해당 부분 조건에 대해 보다 명확한 의미를 부여할 수 있으면 좋겠단 생각이 드네요 감사합니다~

2022-04-08 15:42 UTC, jinsu4755 commented on Seminar1/randomDinnerMatching/random.ts
> +const dinnerMatcher: DinnerMatcher = new SoptDinnerMatcher(memberDataSource);
결국 SoptDinnerMatcher 는 dataSource 를 주입받는 느낌으로 사용하고자 했습니다.
따라서 사실상 직접 주입은 큰 상관이 없지만 시간이 없어 마저 다 작성하지 못했으나
수동 종속성 주입을 생각하며 따로 적은 부분이 있긴 합니다

2022-04-09 06:46 UTC, HYOSITIVE reviewed
벌써부터 다르시군요... 킹갓진수

2022-04-09 06:46 UTC, HYOSITIVE commented on Seminar1/interface.ts
> +        age: 18,
수정해주세요

2022-04-09 06:46 UTC, HYOSITIVE commented on Seminar1/randomDinnerMatching/data/MemberDataSource.ts
> +import {SOPT_GROUP, SoptMember} from "../domain/model/SoptMember";
보통 이런 거 있으면 { 뒤랑 } 앞에 한 칸씩 띄워서 많이 써!

2022-04-09 06:46 UTC, HYOSITIVE commented on Seminar1/randomDinnerMatching/domain/dinnerMatcher.ts
> +import {SOPT_GROUP, SoptMember} from "./model/SoptMember";
마찬가지로 여기도 공백 넣어주세용

2022-04-09 06:46 UTC, HYOSITIVE commented on Seminar1/randomDinnerMatching/domain/model/DinnerMember.ts
> +import {SoptMember} from "./SoptMember";
여기도!

2022-04-09 06:46 UTC, HYOSITIVE commented on Seminar1/randomDinnerMatching/domain/model/SoptMember.ts
> +type SOPT_GROUP = typeof SOPT_GROUP[keyof typeof SOPT_GROUP];
이건 첨보는건데 설명해주라 ㅎㅎ

2022-04-09 06:46 UTC, HYOSITIVE commented on Seminar1/randomDinnerMatching/random.ts
> +import {DinnerMatcher, SoptDinnerMatcher} from "./domain/dinnerMatcher";
띄워주세용~

2022-04-09 06:59 UTC, jinsu4755 commented on Seminar1/interface.ts
> +        age: 18,
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ먼소린가 했네ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-04-09 06:59 UTC, jinsu4755 commented on Seminar1/randomDinnerMatching/data/MemberDataSource.ts
> +import {SOPT_GROUP, SoptMember} from "../domain/model/SoptMember";
아 맞지 자동 정렬 너무 믿고 적어서 그런가보다

2022-04-09 07:11 UTC, jinsu4755 commented on Seminar1/randomDinnerMatching/domain/model/SoptMember.ts
> +type SOPT_GROUP = typeof SOPT_GROUP[keyof typeof SOPT_GROUP];
https://icerabbit.tistory.com/94
나도 잘 몰라서...설명은 그렇다고 해 나도 타스 처음인데 이넘이 타스에있기 때문에 자스로 변경되면 문제가 있다는 말 때문에 알아보고 작성해봤음...ㅋㅋㅋ

2022-04-09 09:13 UTC, epitone commented on Seminar1/randomDinnerMatching/domain/model/SoptMember.ts
> +type SOPT_GROUP = typeof SOPT_GROUP[keyof typeof SOPT_GROUP];
@jinsu4755 

참고하시오..

[TypeScript enum을 사용하지 않는 게 좋은 이유를 Tree-shaking 관점에서 소개합니다.](https://engineering.linecorp.com/ko/blog/typescript-enum-tree-shaking/)
[TypeScript enum을 사용하는 이유](https://medium.com/@seungha_kim_IT/typescript-enum%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0-3b3ccd8e5552)

2022-04-11 07:36 UTC, jinsu4755 commented on Seminar1/randomDinnerMatching/domain/model/SoptMember.ts
> +type SOPT_GROUP = typeof SOPT_GROUP[keyof typeof SOPT_GROUP];
저거 둘다 봄

2022-04-11 08:08 UTC, merged